language: python
python: 3.6

sudo: required
dist: trusty

services:
  - redis-server

branches:
  only:
    - master

env:
  - TOX_ENV=py27
  - TOX_ENV=py35
  - TOX_ENV=py36

install:
- pip install tox

script:
    tox -e $TOX_ENV
